<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFoGJfgP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFoGJfgP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFoGJfgP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFoGJfgP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFoGJfgP\App_KernelDevDebugContainer([
    'container.build_hash' => 'FoGJfgP',
    'container.build_id' => 'b6c3600b',
    'container.build_time' => 1690537741,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFoGJfgP');
