<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGlqBDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGlqBDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGlqBDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGlqBDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXGlqBDx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XGlqBDx',
    'container.build_id' => '8726019c',
    'container.build_time' => 1689592592,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGlqBDx');
