<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGgaaxCA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGgaaxCA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGgaaxCA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGgaaxCA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGgaaxCA\App_KernelDevDebugContainer([
    'container.build_hash' => 'GgaaxCA',
    'container.build_id' => 'a9a2865c',
    'container.build_time' => 1689754565,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGgaaxCA');
